Repository opentelekomcloud/python-otcextensions, pull requests merged in 2021-06, with the labels that each got.

#154 Fix error message for showing missing cluster
  otcextensions/osclient/cce/v2/cluster.py
  otcextensions/tests/unit/osclient/cce/v2/test_cluster.py
Labels: gate

#182 Add SMN service
  doc/source/cli/index.rst
  doc/source/cli/smn.rst
  doc/source/sdk/guides/index.rst
  doc/source/sdk/guides/smn.rst
  doc/source/sdk/proxies/index.rst
  doc/source/sdk/proxies/smn.rst
  doc/source/sdk/resources/index.rst
  doc/source/sdk/resources/smn/index.rst
  doc/source/sdk/resources/smn/v2/message.rst
  doc/source/sdk/resources/smn/v2/sms.rst
  doc/source/sdk/resources/smn/v2/subscription.rst
  doc/source/sdk/resources/smn/v2/template.rst
  doc/source/sdk/resources/smn/v2/topic.rst
  examples/smn/create_subscription.py
  examples/smn/create_template.py
  examples/smn/create_topic.py
  examples/smn/delete_subscription.py
  examples/smn/delete_template.py
  examples/smn/delete_topic.py
  examples/smn/delete_topic_attribute.py
  examples/smn/find_template.py
  examples/smn/get_template.py
  examples/smn/get_topic.py
  examples/smn/list_subscriptions.py
  examples/smn/list_templates.py
  examples/smn/list_topic_attributes.py
  examples/smn/list_topics.py
  examples/smn/publish_message.py
  examples/smn/send_sms.py
  examples/smn/update_template.py
  examples/smn/update_topic.py
  examples/smn/update_topic_attribute.py
  otcextensions/osclient/smn/__init__.py
  otcextensions/osclient/smn/client.py
  otcextensions/osclient/smn/v2/__init__.py
  otcextensions/osclient/smn/v2/message.py
  otcextensions/osclient/smn/v2/sms.py
  otcextensions/osclient/smn/v2/subscription.py
  otcextensions/osclient/smn/v2/template.py
  otcextensions/osclient/smn/v2/topic.py
  otcextensions/sdk/smn/v2/_proxy.py
  otcextensions/sdk/smn/v2/message.py
  otcextensions/sdk/smn/v2/sms.py
  otcextensions/sdk/smn/v2/subscription.py
  otcextensions/sdk/smn/v2/template.py
  otcextensions/sdk/smn/v2/topic.py
  otcextensions/tests/unit/osclient/smn/__init__.py
  otcextensions/tests/unit/osclient/smn/v2/__init__.py
  otcextensions/tests/unit/osclient/smn/v2/fakes.py
  otcextensions/tests/unit/osclient/smn/v2/test_subscription.py
  otcextensions/tests/unit/osclient/smn/v2/test_template.py
  otcextensions/tests/unit/osclient/smn/v2/test_topic.py
  otcextensions/tests/unit/sdk/smn/v2/test_message.py
  otcextensions/tests/unit/sdk/smn/v2/test_proxy.py
  otcextensions/tests/unit/sdk/smn/v2/test_sms.py
  otcextensions/tests/unit/sdk/smn/v2/test_subscription.py
  otcextensions/tests/unit/sdk/smn/v2/test_template.py
  otcextensions/tests/unit/sdk/smn/v2/test_topic.py
  setup.cfg
Labels: enhancement, gate

#184 CCE cloud layer minor fixes for network and enhanced example
  examples/cce/create_cluster_node_cloud_layer.py
  examples/cce/create_node_pool_cloud_layer.py
  otcextensions/sdk/cloud/cce.py
Labels: bug, enhancement, gate

#186 CCE client fixes due to changes on cloud layer
  otcextensions/osclient/cce/v2/cluster_node.py
  otcextensions/osclient/cce/v2/node_pool.py
  otcextensions/tests/unit/osclient/cce/v2/test_cluster_node.py
  otcextensions/tests/unit/osclient/cce/v2/test_node_pool.py
Labels: enhancement, gate

#188 Delete "enterprise_project_id" parameter
  otcextensions/sdk/auto_scaling/v1/group.py
  otcextensions/sdk/cbr/v3/_proxy.py
  otcextensions/sdk/cbr/v3/backup.py
  otcextensions/sdk/cbr/v3/vault.py
  otcextensions/tests/unit/sdk/auto_scaling/v1/test_group.py
  otcextensions/tests/unit/sdk/cbr/v3/test_backup.py
  otcextensions/tests/unit/sdk/dms/v1/test_instance.py
Labels: gate

#189 DNS cleanup private/public zones and ptr records
  otcextensions/sdk/dns/v2/_proxy.py
Labels: gate

#192 Start using zuul template
  .zuul.yaml
Labels: gate

#190 Update `README.rst` and `.gitignore`
  .gitignore
  README.rst
Labels: gate

#193 verify to verify2
  otcextensions/tests/unit/sdk/ces/v1/test_proxy.py
  otcextensions/tests/unit/sdk/dms/v1/test_proxy.py
  otcextensions/tests/unit/sdk/rds/v3/test_proxy.py
  otcextensions/tests/unit/sdk/vpc/v2/test_proxy.py
Labels: gate

#185 Dns functional tests
  otcextensions/tests/functional/sdk/dns/__init__.py
  otcextensions/tests/functional/sdk/dns/v2/__init__.py
  otcextensions/tests/functional/sdk/dns/v2/test_floatingips.py
  otcextensions/tests/functional/sdk/dns/v2/test_nameservers.py
  otcextensions/tests/functional/sdk/dns/v2/test_recordsets.py
  otcextensions/tests/functional/sdk/dns/v2/test_service.py
  otcextensions/tests/functional/sdk/dns/v2/test_zone.py
Labels: gate

#198 Do not use toc in the RN
  releasenotes/source/conf.py
Labels: gate

#200 DDS flavors
  doc/source/sdk/proxies/dds_v3.rst
  doc/source/sdk/resources/dds/index.rst
  doc/source/sdk/resources/dds/v3/flavor.rst
  otcextensions/sdk/dds/v3/_proxy.py
  otcextensions/sdk/dds/v3/flavor.py
  otcextensions/tests/functional/sdk/dds/v3/test_flavor.py
  otcextensions/tests/functional/sdk/waf/v1/test_domain.py
  otcextensions/tests/unit/sdk/dds/v3/test_flavor.py
  releasenotes/notes/add-dds-flavors-2c48049ac2a06330.yaml
Labels: gate

#202 Fix tearDown in test fixtures
  otcextensions/tests/functional/sdk/auto_scaling/v1/base.py
  otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
  otcextensions/tests/functional/sdk/dms/v1/test_instance.py
  otcextensions/tests/functional/sdk/dms/v1/test_message.py
  otcextensions/tests/functional/sdk/dms/v1/test_queue.py
  otcextensions/tests/functional/sdk/dns/v2/test_floatingips.py
  otcextensions/tests/functional/sdk/dns/v2/test_nameservers.py
  otcextensions/tests/functional/sdk/dns/v2/test_recordsets.py
  otcextensions/tests/functional/sdk/dns/v2/test_zone.py
  otcextensions/tests/functional/sdk/kms/v1/test_data_key.py
Labels: gate
