Repository opentelekomcloud/python-otcextensions, pull requests merged in 2021-04, with the labels that each got.

#163 fix issue 162
  otcextensions/sdk/dms/v1/message.py
  otcextensions/tests/unit/sdk/dms/v1/test_proxy.py
Labels: bug, gate

#159 [CLI] Initialize cloud layer in CCE and RDS
  otcextensions/osclient/cce/v2/cluster.py
  otcextensions/osclient/rds/v3/instance.py
Labels: gate

#127 Use openstack proxy for kms service
  doc/source/sdk/guides/kms.rst
  examples/kms/create_datakey.py
  examples/kms/create_datakey_without_plaintext.py
  examples/kms/decrypt_datakey.py
  examples/kms/encrypt_datakey.py
  otcextensions/sdk/kms/kms_service.py
  otcextensions/sdk/kms/v1/_base.py
  otcextensions/sdk/kms/v1/_proxy.py
  otcextensions/sdk/kms/v1/data_key.py
  otcextensions/sdk/kms/v1/key.py
  otcextensions/sdk/kms/v1/misc.py
  otcextensions/tests/functional/sdk/kms/v1/test_data_key.py
  otcextensions/tests/functional/sdk/kms/v1/test_key.py
  otcextensions/tests/unit/sdk/kms/v1/test_data_key.py
  otcextensions/tests/unit/sdk/kms/v1/test_key.py
  otcextensions/tests/unit/sdk/kms/v1/test_misc.py
  otcextensions/tests/unit/sdk/kms/v1/test_proxy.py
Labels: gate

#166 one css example for a customer request
  examples/css/create_cluster.py
Labels: enhancement, gate

#168 Bring back iam in osc
  doc/source/cli/identity.rst
  doc/source/sdk/proxies/identity_v3.rst
  examples/identity/create_security_token.py
  otcextensions/osclient/identity/client.py
  otcextensions/osclient/identity/v3/credential.py
  otcextensions/sdk/identity/v3/_proxy.py
  otcextensions/sdk/identity/v3/security_token.py
  otcextensions/tests/unit/osclient/identity/v3/fakes.py
  otcextensions/tests/unit/sdk/identity/v3/test_proxy.py
  setup.cfg
Labels: gate

#169 CBR vault SDK resource
  doc/source/sdk/guides/cbr.rst
  doc/source/sdk/proxies/cbr.rst
  doc/source/sdk/resources/cbr/index.rst
  doc/source/sdk/resources/cbr/v3/vault.rst
  examples/cbr/associate_resources.py
  examples/cbr/bind_policy.py
  examples/cbr/create_vault.py
  examples/cbr/delete_vault.py
  examples/cbr/dissociate_resources.py
  examples/cbr/find_vault.py
  examples/cbr/get_vault.py
  examples/cbr/list_vaults.py
  examples/cbr/unbind_policy.py
  examples/cbr/update_vault.py
  otcextensions/sdk/cbr/v3/_proxy.py
  otcextensions/sdk/cbr/v3/vault.py
  otcextensions/tests/unit/sdk/cbr/v3/test_proxy.py
  otcextensions/tests/unit/sdk/cbr/v3/test_vault.py
Labels: gate

#171 added endpoint_overrided to get_container method in proxy
  otcextensions/sdk/obs/v1/_proxy.py
Labels: gate

#172 Fix metric naming for the OBS
  otcextensions/sdk/obs/v1/_proxy.py
  otcextensions/tests/unit/sdk/obs/v1/test_proxy.py
Labels: gate
