Repository opentelekomcloud/python-otcextensions, pull requests merged in 2021-03, with the labels that each got.

#139 CBR checkpoint, policy resources
  doc/source/sdk/guides/cbr.rst
  doc/source/sdk/proxies/cbr.rst
  doc/source/sdk/resources/cbr/index.rst
  doc/source/sdk/resources/cbr/v3/backup.rst
  doc/source/sdk/resources/cbr/v3/checkpoint.rst
  doc/source/sdk/resources/cbr/v3/policy.rst
  examples/cbr/create_checkpoint.py
  examples/cbr/create_policy.py
  examples/cbr/delete_policy.py
  examples/cbr/find_policy.py
  examples/cbr/get_checkpoint.py
  examples/cbr/get_policy.py
  examples/cbr/list_policies.py
  examples/cbr/update_policy.py
  otcextensions/sdk/cbr/v3/_proxy.py
  otcextensions/sdk/cbr/v3/checkpoint.py
  otcextensions/sdk/cbr/v3/policy.py
  otcextensions/tests/unit/sdk/cbr/v3/test_checkpoint.py
  otcextensions/tests/unit/sdk/cbr/v3/test_policy.py
  otcextensions/tests/unit/sdk/cbr/v3/test_proxy.py
Labels: enhancement, gate

#142 Fix print and debug issues
  otcextensions/osclient/auto_scaling/v1/policy.py
  otcextensions/osclient/cce/v2/node_pool.py
  otcextensions/osclient/dcs/v1/config.py
  otcextensions/sdk/cce/v1/cluster.py
  otcextensions/sdk/dcs/v1/backup.py
  otcextensions/tests/functional/sdk/cce/v1/test_cluster.py
  otcextensions/tests/functional/sdk/deh/v1/test_host.py
  otcextensions/tests/functional/sdk/dms/v1/test_message.py
  otcextensions/tests/functional/sdk/elb/__init__.py
  otcextensions/tests/functional/sdk/nat/v2/test_dnat.py
  otcextensions/tests/functional/sdk/nat/v2/test_gateway.py
  otcextensions/tests/functional/sdk/nat/v2/test_snat.py
  otcextensions/tests/functional/sdk/waf/__init__.py
  otcextensions/tests/unit/osclient/cce/v1/test_cluster.py
Labels: bug, gate

#153 minor changes for installation advices
  doc/source/install/pip_install.rst
Labels: gate

#157 Dcs fixes
  doc/source/sdk/guides/dcs.rst
  examples/dcs/change_instance_password.py
  examples/dcs/delete_backup.py
  examples/dcs/list_instance_params.py
  examples/dcs/update_instance_params.py
  otcextensions/sdk/dcs/v1/_proxy.py
  otcextensions/tests/unit/osclient/rds/v3/test_instance.py
  otcextensions/tests/unit/sdk/dcs/v1/test_proxy.py
Labels: gate

#156 DMS Examples & Docu
  doc/source/sdk/guides/cce.rst
  doc/source/sdk/guides/dms.rst
  doc/source/sdk/guides/index.rst
  examples/dms/confirm_message.py
  examples/dms/consume_message.py
  examples/dms/create_instance.py
  examples/dms/create_instance_topic.py
  examples/dms/create_queue.py
  examples/dms/create_queue_group.py
  examples/dms/delete_instance.py
  examples/dms/delete_instance_topic.py
  examples/dms/delete_queue.py
  examples/dms/delete_queue_group.py
  examples/dms/find_instance.py
  examples/dms/find_queue.py
  examples/dms/find_queue_group.py
  examples/dms/get_instance.py
  examples/dms/get_queue.py
  examples/dms/list_instance_az_zones.py
  examples/dms/list_instance_products.py
  examples/dms/list_instance_topics.py
  examples/dms/list_instances.py
  examples/dms/list_maintenance_windows.py
  examples/dms/list_queue_groups.py
  examples/dms/list_queues.py
  examples/dms/restart_instance.py
  examples/dms/send_messages.py
  examples/dms/update_instance.py
Labels: enhancement, gate

#158 Auto scaling find instance
  otcextensions/sdk/auto_scaling/v1/_proxy.py
  otcextensions/sdk/auto_scaling/v1/instance.py
  otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
  otcextensions/tests/unit/sdk/auto_scaling/v1/test_proxy.py
Labels: gate

#161 fix issue #84
  otcextensions/osclient/obs/v1/container.py
Labels: gate
