Repository opentelekomcloud/python-otcextensions, pull requests merged in 2021-05, with the labels that each got.

#174 CBR share member SDK
  doc/source/sdk/guides/cbr.rst
  doc/source/sdk/proxies/cbr.rst
  doc/source/sdk/resources/cbr/index.rst
  doc/source/sdk/resources/cbr/v3/member.rst
  examples/cbr/add_member.py
  examples/cbr/delete_member.py
  examples/cbr/get_member.py
  examples/cbr/list_members.py
  examples/cbr/update_member.py
  otcextensions/sdk/cbr/v3/_proxy.py
  otcextensions/sdk/cbr/v3/backup.py
  otcextensions/sdk/cbr/v3/member.py
  otcextensions/sdk/cbr/v3/restore.py
  otcextensions/tests/unit/osclient/load_balancer/v1/test_pool_member.py
  otcextensions/tests/unit/sdk/cbr/v3/test_backup.py
  otcextensions/tests/unit/sdk/cbr/v3/test_member.py
  otcextensions/tests/unit/sdk/cbr/v3/test_proxy.py
Labels: enhancement, gate

#175 Adding wait methods for as_instance and as_group
  otcextensions/sdk/auto_scaling/v1/_proxy.py
  otcextensions/tests/functional/sdk/auto_scaling/v1/test_instance.py
Labels: gate

#177 status field added
  otcextensions/osclient/cce/v2/node_pool.py
  otcextensions/tests/unit/osclient/cce/v2/test_node_pool.py
Labels: enhancement, gate

#178 Adding new properties and new unit test
  otcextensions/sdk/auto_scaling/v1/group.py
  otcextensions/tests/unit/sdk/auto_scaling/v1/test_group.py
Labels: gate

#180 Fix issue #97
  doc/source/sdk/resources/dcs/index.rst
  doc/source/sdk/resources/dcs/v1/restore.rst
  doc/source/sdk/resources/dcs/v1/restore_record.rst
  otcextensions/osclient/dcs/v1/restore_record.py
  otcextensions/sdk/dcs/v1/_proxy.py
  otcextensions/sdk/dcs/v1/restore_record.py
  otcextensions/tests/unit/osclient/dcs/v1/fakes.py
  otcextensions/tests/unit/osclient/dcs/v1/test_restore.py
  otcextensions/tests/unit/sdk/dcs/v1/test_proxy.py
  otcextensions/tests/unit/sdk/dcs/v1/test_restore_record.py
Labels: bug, gate
