Repository opentelekomcloud/python-otcextensions, pull requests merged in 2024-02, with the labels that each got.

#404 [SWR] organization implementation, refactoring and extract_name
  .stestr.blacklist.functional
  doc/source/sdk/proxies/index.rst
  doc/source/sdk/proxies/swr.rst
  doc/source/sdk/resources/index.rst
  doc/source/sdk/resources/swr/index.rst
  doc/source/sdk/resources/swr/v2/organization.rst
  examples/swr/create_organization.py
  examples/swr/delete_organization.py
  examples/swr/get_organization.py
  examples/swr/list_organizations.py
  otcextensions/sdk/__init__.py
  otcextensions/sdk/swr/__init__.py
  otcextensions/sdk/swr/swr_service.py
  otcextensions/sdk/swr/v2/__init__.py
  otcextensions/sdk/swr/v2/_proxy.py
  otcextensions/sdk/swr/v2/domain.py
  otcextensions/sdk/swr/v2/organization.py
  otcextensions/sdk/swr/v2/repository.py
  otcextensions/tests/functional/sdk/swr/__init__.py
  otcextensions/tests/functional/sdk/swr/v2/__init__.py
  otcextensions/tests/functional/sdk/swr/v2/test_organization.py
  otcextensions/tests/functional/sdk/swr/v2/test_service.py
  otcextensions/tests/unit/sdk/swr/__init__.py
  otcextensions/tests/unit/sdk/swr/v1/__init__.py
  otcextensions/tests/unit/sdk/swr/v1/test_organization.py
  otcextensions/tests/unit/sdk/swr/v1/test_proxy.py
Labels: enhancement, gate

#408 [OBS]: Folder creation and management fix
  otcextensions/sdk/obs/v1/_proxy.py
  otcextensions/sdk/obs/v1/obj.py
  otcextensions/tests/functional/sdk/obs/v1/test_object.py
Labels: gate

#402 CSS cluster minor update
  examples/css/create_cluster_opensearch.py
  otcextensions/osclient/css/v1/cluster.py
Labels: gate

#410 [SWR] repository
  doc/source/sdk/proxies/swr.rst
  doc/source/sdk/resources/swr/index.rst
  doc/source/sdk/resources/swr/v2/repository.rst
  examples/swr/create_repository.py
  examples/swr/delete_repository.py
  examples/swr/get_repository.py
  examples/swr/list_repository.py
  examples/swr/update_repository.py
  otcextensions/sdk/swr/v2/_proxy.py
  otcextensions/sdk/swr/v2/organization.py
  otcextensions/sdk/swr/v2/repository.py
  otcextensions/tests/functional/sdk/swr/v2/test_repository.py
  otcextensions/tests/unit/sdk/swr/v1/test_organization.py
  otcextensions/tests/unit/sdk/swr/v2/__init__.py
  otcextensions/tests/unit/sdk/swr/v2/test_organization.py
  otcextensions/tests/unit/sdk/swr/v2/test_proxy.py
  otcextensions/tests/unit/sdk/swr/v2/test_repository.py
  releasenotes/notes/swr-repository-3b69cd079b613528.yaml
Labels: enhancement, gate, demand

#411 [SWR] repository permissions
  doc/source/sdk/proxies/swr.rst
  doc/source/sdk/resources/swr/v2/repository.rst
  otcextensions/sdk/swr/v2/_base.py
  otcextensions/sdk/swr/v2/_proxy.py
  otcextensions/sdk/swr/v2/organization.py
  otcextensions/sdk/swr/v2/repository.py
  otcextensions/tests/functional/sdk/swr/v2/test_repository.py
  otcextensions/tests/unit/sdk/swr/v2/test_proxy.py
  otcextensions/tests/unit/sdk/swr/v2/test_repository.py
  releasenotes/notes/swr-repository-permissions-e27a95e4e1b18a6b.yaml
  tox.ini
Labels: enhancement, gate, demand

#412 [SWR] domain
  doc/source/sdk/proxies/swr.rst
  doc/source/sdk/resources/swr/index.rst
  doc/source/sdk/resources/swr/v2/domain.rst
  examples/swr/create_domain.py
  examples/swr/delete_domain.py
  examples/swr/get_domain.py
  examples/swr/list_domain.py
  examples/swr/update_domain.py
  otcextensions/sdk/swr/v2/_proxy.py
  otcextensions/sdk/swr/v2/domain.py
  otcextensions/tests/functional/sdk/swr/v2/test_domain.py
  otcextensions/tests/unit/sdk/swr/v2/test_domain.py
  otcextensions/tests/unit/sdk/swr/v2/test_proxy.py
  releasenotes/notes/swr-domain-f440d14f651aad18.yaml
Labels: enhancement, gate, demand

#415 change README links
  README.rst
Labels: gate
