Repository opentelekomcloud/python-otcextensions, pull requests merged in 2024-05, with the labels that each got.

#431 427 resource tags
  .stestr.blacklist.functional
  doc/source/sdk/proxies/tms.rst
  doc/source/sdk/resources/tms/index.rst
  doc/source/sdk/resources/tms/v1/resource_tag.rst
  examples/tms/add_resource_tag.py
  examples/tms/delete_resource_tag.py
  examples/tms/list_resource_tag.py
  otcextensions/sdk/tms/v1/_proxy.py
  otcextensions/sdk/tms/v1/resource_tag.py
  otcextensions/tests/functional/sdk/auto_scaling/v1/test_quota.py
  otcextensions/tests/functional/sdk/nat/v2/test_dnat.py
  otcextensions/tests/functional/sdk/nat/v2/test_snat.py
  otcextensions/tests/functional/sdk/tms/v1/test_resource_tags.py
  otcextensions/tests/unit/sdk/tms/v1/test_proxy.py
  otcextensions/tests/unit/sdk/tms/v1/test_resource_tag.py
  releasenotes/notes/resource_tags-5e45d9f7de9ec463.yaml
Labels: gate

#433 fix issue with dns zone args #430
  otcextensions/osclient/dns/v2/zone.py
  otcextensions/tests/unit/osclient/dns/v2/test_zone.py
Labels: bug, gate

#435 [compute] fixed assignment of server tags
  otcextensions/sdk/__init__.py
  otcextensions/sdk/compute/v2/server.py
  otcextensions/tests/functional/sdk/compute/v2/__init__.py
  otcextensions/tests/functional/sdk/compute/v2/test_server_tag.py
  otcextensions/tests/functional/sdk/compute/v2/test_service.py
  otcextensions/tests/unit/sdk/compute/v2/test_server.py
Labels: bug, gate

#437 434 create an image ims
  .stestr.blacklist.functional
  doc/source/sdk/proxies/ims.rst
  doc/source/sdk/proxies/index.rst
  doc/source/sdk/resources/ims/index.rst
  doc/source/sdk/resources/ims/v2/image.rst
  doc/source/sdk/resources/index.rst
  examples/ims/__init__.py
  examples/ims/create_image_from_obs.py
  otcextensions/sdk/__init__.py
  otcextensions/sdk/ims/__init__.py
  otcextensions/sdk/ims/ims_service.py
  otcextensions/sdk/ims/v2/__init__.py
  otcextensions/sdk/ims/v2/_proxy.py
  otcextensions/sdk/ims/v2/image.py
  otcextensions/tests/functional/sdk/ims/__init__.py
  otcextensions/tests/functional/sdk/ims/v2/__init__.py
  otcextensions/tests/functional/sdk/ims/v2/test_image.py
  otcextensions/tests/functional/sdk/ims/v2/test_service.py
  otcextensions/tests/unit/sdk/ims/__init__.py
  otcextensions/tests/unit/sdk/ims/v2/__init__.py
  otcextensions/tests/unit/sdk/ims/v2/test_image.py
  otcextensions/tests/unit/sdk/ims/v2/test_proxy.py
Labels: enhancement, gate

#440 adding sdk proxies for enterprise dashboard
  otcextensions/sdk/__init__.py
  otcextensions/sdk/enterprise_dashboard/__init__.py
  otcextensions/sdk/enterprise_dashboard/enterprise_dashboard_service.py
  otcextensions/sdk/enterprise_dashboard/v1/__init__.py
  otcextensions/sdk/enterprise_dashboard/v1/_proxy.py
  otcextensions/sdk/enterprise_dashboard_v1/__init__.py
  otcextensions/sdk/enterprise_dashboard_v1/enterprise_dashboard_v1_service.py
  otcextensions/sdk/enterprise_dashboard_v1/v1/__init__.py
  otcextensions/sdk/enterprise_dashboard_v1/v1/_proxy.py
Labels: gate
