Repository opentelekomcloud/python-otcextensions, pull requests merged in 2024-11, with the labels that each got.

#481 add .readthedocs.yaml for readthedocs configuration
  .readthedocs.yaml
Labels: gate

#484 mod rtd cfg
  .readthedocs.yaml
Labels: gate

#485 chg req file for rtd and enable warnings
  .readthedocs.yaml
Labels: gate

#489 Update rtfd_requirements.txt
  doc/rtfd_requirements.txt
Labels: gate

#487 CTS v3 query traces implemented
  doc/source/sdk/proxies/cts_v3.rst
  doc/source/sdk/resources/cts/index.rst
  doc/source/sdk/resources/cts/v3/trace.rst
  examples/ctsv3/list_traces.py
  otcextensions/sdk/ctsv3/v3/_proxy.py
  otcextensions/sdk/ctsv3/v3/trace.py
  otcextensions/tests/functional/sdk/ctsv3/v3/test_traces.py
  otcextensions/tests/unit/sdk/ctsv3/v3/test_proxy.py
  otcextensions/tests/unit/sdk/ctsv3/v3/test_traces.py
Labels: enhancement, gate

#491 [Feat.] Missing proxies for er, fg and apig
  otcextensions/sdk/__init__.py
  otcextensions/sdk/apig/__init__.py
  otcextensions/sdk/apig/apig_service.py
  otcextensions/sdk/apig/v2/__init__.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/er/__init__.py
  otcextensions/sdk/er/er_service.py
  otcextensions/sdk/er/v3/__init__.py
  otcextensions/sdk/er/v3/_proxy.py
  otcextensions/sdk/function_graph/__init__.py
  otcextensions/sdk/function_graph/function_graph_service.py
  otcextensions/sdk/function_graph/v2/__init__.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/sdk_make_proxy.py
  otcextensions/tests/functional/sdk/apig/__init__.py
  otcextensions/tests/functional/sdk/apig/v2/__init__.py
  otcextensions/tests/functional/sdk/apig/v2/test_service.py
  otcextensions/tests/functional/sdk/er/__init__.py
  otcextensions/tests/functional/sdk/er/v3/__init__.py
  otcextensions/tests/functional/sdk/er/v3/test_service.py
  otcextensions/tests/functional/sdk/function_graph/__init__.py
  otcextensions/tests/functional/sdk/function_graph/v2/__init__.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_service.py
  releasenotes/notes/proxies-apig-fg-er-f939b4523f23b031.yaml
Labels: gate

#492 Add query operations for public/target VPC endpoint services
  doc/source/sdk/proxies/vpcep.rst
  examples/vpcep/get_public_services.py
  examples/vpcep/get_target_service.py
  otcextensions/sdk/vpcep/v1/_proxy.py
  otcextensions/sdk/vpcep/v1/public_service.py
  otcextensions/sdk/vpcep/v1/target_service.py
  otcextensions/tests/unit/sdk/vpcep/v1/test_proxy.py
  otcextensions/tests/unit/sdk/vpcep/v1/test_public_service.py
  otcextensions/tests/unit/sdk/vpcep/v1/test_target_service.py
  releasenotes/notes/vpcep-target-endpoint-services-ddbab96f411fe1bc.yaml
Labels: gate

#493 490 cts v3 tracker management
  .stestr.blacklist.functional
  doc/source/sdk/proxies/cts_v3.rst
  doc/source/sdk/resources/cts/index.rst
  doc/source/sdk/resources/cts/v3/quota.rst
  doc/source/sdk/resources/cts/v3/tracker.rst
  examples/ctsv3/create_tracker.py
  examples/ctsv3/delete_tracker.py
  examples/ctsv3/list_quotas.py
  examples/ctsv3/list_trackers.py
  otcextensions/sdk/ctsv3/v3/_proxy.py
  otcextensions/sdk/ctsv3/v3/quota.py
  otcextensions/sdk/ctsv3/v3/tracker.py
  otcextensions/tests/functional/sdk/ctsv3/v3/test_quotas.py
  otcextensions/tests/functional/sdk/ctsv3/v3/test_tracker.py
  otcextensions/tests/unit/sdk/ctsv3/v3/test_proxy.py
  otcextensions/tests/unit/sdk/ctsv3/v3/test_quota.py
  otcextensions/tests/unit/sdk/ctsv3/v3/test_tracker.py
  releasenotes/notes/add_v3_cts-5243f93d53d2fcbb.yaml
Labels: enhancement, gate

#494 adding correct extract of name for services
  otcextensions/common/utils.py
  otcextensions/sdk/anti_ddos/v1/_proxy.py
  otcextensions/sdk/bms/v1/_proxy.py
  otcextensions/sdk/dcaas/v2/_proxy.py
  otcextensions/sdk/ecs/v1/_proxy.py
  otcextensions/sdk/elb/v2/_proxy.py
  otcextensions/sdk/enterprise_dashboard/v1/_proxy.py
  otcextensions/sdk/enterprise_dashboard_v1/v1/_proxy.py
  otcextensions/sdk/er/v3/_proxy.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/kms/v1/_proxy.py
  otcextensions/sdk/smn/__init_.py
  otcextensions/sdk/smn/v2/_proxy.py
  otcextensions/sdk/swr/v2/_proxy.py
  otcextensions/sdk/vlb/v3/_proxy.py
  otcextensions/sdk/vpc/v1/_proxy.py
  otcextensions/sdk/waf/v1/_proxy.py
  otcextensions/sdk/wafd/v1/_proxy.py
Labels: gate

#497 rm failing _extract_name method from vpc
  otcextensions/common/utils.py
  otcextensions/tests/unit/sdk/vpc/v1/test_proxy.py
Labels: bug, gate

#495 cleanup dms implemented partially
  .stestr.blacklist.functional
  otcextensions/sdk/dms/v1/_proxy.py
  otcextensions/tests/functional/sdk/dms/v1/test_cleanup.py
Labels: gate

#498 Fixing extracting metric path for SFS Turbo
  otcextensions/sdk/sfsturbo/v1/_proxy.py
  otcextensions/tests/unit/test_stats.py
Labels: bug, gate
