Repository opentelekomcloud/python-otcextensions, pull requests merged in 2025-07, with the labels that each got.

#591 fix TypeError when segment size exceeds DEFAULT_MAX_FILE_SIZE
  otcextensions/sdk/obs/v1/_proxy.py
Labels: gate

#530 Updating images in IMSv2
  otcextensions/sdk/imsv2/v2/_proxy.py
  otcextensions/sdk/imsv2/v2/image.py
  otcextensions/tests/functional/sdk/imsv2/v2/test_image.py
  releasenotes/notes/imsv2_updating_images-c21abfa5f963a4d3.yaml
Labels: gate

#593 [Fix] listing cbr vaults
  otcextensions/osclient/cbr/v3/vault.py
  otcextensions/tests/functional/osclient/cbr/__init__.py
  otcextensions/tests/functional/osclient/cbr/v3/__init__.py
  otcextensions/tests/functional/osclient/cbr/v3/test_task.py
  otcextensions/tests/functional/osclient/cbr/v3/test_vault.py
  otcextensions/tests/functional/sdk/cbr/v3/test_vault.py
  otcextensions/tests/unit/osclient/cbr/v3/fakes.py
  otcextensions/tests/unit/osclient/cbr/v3/test_vault.py
  releasenotes/notes/cli-cbr-vaults-fix-6a91f9543d5e765u.yaml
Labels: bug, gate

#598 feat(apig-group-response): add management
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/error_response.rst
  doc/source/sdk/resources/apig/v2/group_response.rst
  examples/apig/create_group_response.py
  examples/apig/delete_error_response.py
  examples/apig/delete_group_response.py
  examples/apig/get_error_response.py
  examples/apig/get_group_response.py
  examples/apig/list_group_responses.py
  examples/apig/update_error_response.py
  examples/apig/update_group_response.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/error_response.py
  otcextensions/sdk/apig/v2/group_response.py
  otcextensions/tests/functional/sdk/apig/v2/test_group_response.py
  otcextensions/tests/unit/sdk/apig/v2/test_error_response.py
  otcextensions/tests/unit/sdk/apig/v2/test_group_response.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  releasenotes/notes/apig-group-response-1fd9a4c26b8fa6be.yaml
Labels: enhancement, gate
