Repository opentelekomcloud/python-otcextensions, pull requests merged in 2025-03, with the labels that each got.

#549 [Feat.] APIG Excluded Request Throttling Configuration
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/throttling_excluded.rst
  examples/apig/create_throttling_exclude.py
  examples/apig/delete_throttling_exclude.py
  examples/apig/list_throttling_exclude.py
  examples/apig/update_throttling_exclude.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/throttling_excluded.py
  otcextensions/tests/functional/sdk/apig/v2/test_throttling_excluded_policy.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  otcextensions/tests/unit/sdk/apig/v2/test_throttling_excluded_policy.py
  releasenotes/notes/apig-throttling-exclude-c2e3b041e76c18e9.yaml
Labels: enhancement, gate

#550 [Feat.] APIG Gateway Features
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/gateway_features.rst
  examples/apig/configure_gw_feature.py
  examples/apig/list_gw_features.py
  examples/apig/list_supported_gw_features.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/gateway_features.py
  otcextensions/tests/functional/sdk/apig/v2/test_features.py
  otcextensions/tests/unit/sdk/apig/v2/test_gateway_features.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  releasenotes/notes/apig-gw-features-f53b025851246eac.yaml
Labels: enhancement, gate

#554 [Fix] translate response signature fix
  otcextensions/sdk/cce/v3/_base.py
  otcextensions/sdk/cce/v3/cluster_cert.py
  otcextensions/sdk/ces/v1/alarm.py
  otcextensions/sdk/cts/v1/tracker.py
  otcextensions/sdk/dws/v1/tag.py
  otcextensions/sdk/kms/v1/_base.py
  otcextensions/sdk/modelartsv1/v1/devenv.py
  otcextensions/sdk/modelartsv1/v1/model.py
  otcextensions/sdk/modelartsv1/v1/service.py
  otcextensions/sdk/obs/v1/container.py
  otcextensions/sdk/obs/v1/obj.py
  otcextensions/sdk/rds/v1/configuration.py
  otcextensions/sdk/rds/v3/instance.py
  otcextensions/sdk/sdk_resource.py
  otcextensions/tests/functional/osclient/cce/__init__.py
  otcextensions/tests/functional/osclient/cce/v3/__init__.py
  otcextensions/tests/functional/osclient/cce/v3/test_cluster.py
  otcextensions/tests/unit/osclient/anti_ddos/v1/fakes.py
  releasenotes/notes/sdk-update-fixes-cdd4305163b05f8f.yaml
  requirements.txt
  test-requirements.txt
Labels: bug, enhancement, gate

#551 [Feat.] APIG Resource Query
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/resource_query.rst
  examples/apig/get_api_group_quantities.py
  examples/apig/get_api_quantities.py
  examples/apig/get_app_quantities.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/resource_query.py
  otcextensions/tests/functional/osclient/cce/v3/test_cluster.py
  otcextensions/tests/functional/sdk/apig/v2/test_features.py
  otcextensions/tests/functional/sdk/apig/v2/test_resource_query.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  otcextensions/tests/unit/sdk/apig/v2/test_resource_query.py
  releasenotes/notes/apig-resource-query-bf3f1eac5b23a4fb.yaml
Labels: enhancement, gate

#555 [Feat.] APIG domain name
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/certificate.rst
  doc/source/sdk/resources/apig/v2/domain_name.rst
  examples/apig/bind_domain_name.py
  examples/apig/create_certificate_for_domain.py
  examples/apig/delete_certificate.py
  examples/apig/enable_debug_domain_name.py
  examples/apig/get_bound_certificate.py
  examples/apig/unbind_certificate_from_domain.py
  examples/apig/unbind_domain_name.py
  examples/apig/update_domain_name_bound.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/certificate.py
  otcextensions/sdk/apig/v2/domain_name.py
  otcextensions/tests/functional/sdk/apig/v2/test_domain.py
  otcextensions/tests/ssl.py
  otcextensions/tests/unit/sdk/apig/v2/test_domain.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  releasenotes/notes/apig-domain-name-bc5abb123c0ab71c.yaml
Labels: enhancement, gate

#556 [Feat.] now name and filename attr is supported in multypart upload
  examples/obs/multipart_upload.py
  otcextensions/sdk/obs/v1/_proxy.py
Labels: gate

#558 [Fix] network service_providers method
  .stestr.blacklist.functional
  otcextensions/sdk/__init__.py
  otcextensions/sdk/network/__init__.py
  otcextensions/sdk/network/v2/__init__.py
  otcextensions/sdk/network/v2/_proxy.py
  otcextensions/sdk/network/v2/service_provider.py
  otcextensions/tests/functional/sdk/network/__init__.py
  otcextensions/tests/functional/sdk/network/v2/__init__.py
  otcextensions/tests/functional/sdk/network/v2/test_cleanup.py
Labels: gate

#560 [Fix] service_cleanup signature update
  otcextensions/sdk/anti_ddos/v1/_proxy.py
  otcextensions/sdk/auto_scaling/v1/_proxy.py
  otcextensions/sdk/cce/v3/_proxy.py
  otcextensions/sdk/dns/v2/_proxy.py
  otcextensions/sdk/vpc/v1/_proxy.py
  otcextensions/sdk/waf/v1/_proxy.py
  releasenotes/notes/cleanup-signature-fix-6a1b63706bce6675.yaml
Labels: gate

#559 [Feat.] APIG API Credential Management
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/app.rst
  examples/apig/create_app.py
  examples/apig/create_app_code.py
  examples/apig/delete_app.py
  examples/apig/delete_app_code.py
  examples/apig/generate_app_code.py
  examples/apig/get_app.py
  examples/apig/get_app_code.py
  examples/apig/list_app_codes.py
  examples/apig/list_apps.py
  examples/apig/list_quotas.py
  examples/apig/reset_app_secret.py
  examples/apig/update_app.py
  examples/apig/verify_app.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/app.py
  otcextensions/sdk/apig/v2/appcode.py
  otcextensions/tests/functional/sdk/apig/v2/test_access_control.py
  otcextensions/tests/functional/sdk/apig/v2/test_app.py
  otcextensions/tests/functional/sdk/apig/v2/test_app_code.py
  otcextensions/tests/functional/sdk/apig/v2/test_quota.py
  otcextensions/tests/unit/sdk/apig/v2/test_app.py
  otcextensions/tests/unit/sdk/apig/v2/test_app_code.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  otcextensions/tests/unit/sdk/apig/v2/test_quota.py
Labels: gate

#563 fix(rds): added check for instance.tags
  otcextensions/sdk/rds/v3/_proxy.py
Labels: gate

#564 561 feat apig app authorization
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/api_auth.rst
  examples/apig/authorize_apps.py
  examples/apig/cancel_authorization.py
  examples/apig/list_api_bound_to_app.py
  examples/apig/list_api_not_bound_to_app.py
  examples/apig/list_apps_bound_to_api.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/api_auth.py
  otcextensions/tests/functional/sdk/apig/v2/test_auth.py
  otcextensions/tests/unit/sdk/apig/v2/test_auth.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  releasenotes/notes/apig-api-auth-304638880d32255d.yaml
Labels: gate
