Repository opentelekomcloud/python-otcextensions, pull requests merged in 2025-02, with the labels that each got.

#513 [Feat.] FunctionGraph Aliases and versions
  doc/source/sdk/guides/function_graph.rst
  doc/source/sdk/proxies/function_graph.rst
  doc/source/sdk/resources/function_graph/index.rst
  doc/source/sdk/resources/function_graph/v2/alias.rst
  doc/source/sdk/resources/function_graph/v2/version.rst
  examples/function_graph/create_alias.py
  examples/function_graph/delete_alias.py
  examples/function_graph/get_alias.py
  examples/function_graph/list_aliases.py
  examples/function_graph/list_versions.py
  examples/function_graph/publish_version.py
  examples/function_graph/update_alias.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/function_graph/v2/alias.py
  otcextensions/sdk/function_graph/v2/event.py
  otcextensions/sdk/function_graph/v2/version.py
  otcextensions/tests/functional/sdk/function_graph/__init__.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_alias.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_event.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_alias.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_proxy.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_version.py
  releasenotes/notes/fg-aliases-versions-c0ffbc3d9cda043f.yaml
Labels: enhancement, gate

#514 [Feat.] FunctionGraph metrics
  doc/source/sdk/guides/function_graph.rst
  doc/source/sdk/proxies/function_graph.rst
  doc/source/sdk/resources/function_graph/index.rst
  doc/source/sdk/resources/function_graph/v2/metric.rst
  examples/function_graph/list_function_metrics.py
  examples/function_graph/list_metrics.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/function_graph/v2/metric.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_metric.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_metric.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_proxy.py
  releasenotes/notes/fg-metrics-53f38539a61a84b4.yaml
Labels: enhancement, gate

#519 [Feat] FunctionGraph reserved instances and import/export
  .stestr.blacklist.functional
  doc/source/sdk/guides/function_graph.rst
  doc/source/sdk/proxies/function_graph.rst
  doc/source/sdk/resources/function_graph/index.rst
  doc/source/sdk/resources/function_graph/v2/export.rst
  doc/source/sdk/resources/function_graph/v2/import.rst
  doc/source/sdk/resources/function_graph/v2/reserved_instance.rst
  examples/function_graph/export_function.py
  examples/function_graph/import_function.py
  examples/function_graph/list_reserved_instances.py
  examples/function_graph/list_reserved_instances_config.py
  examples/function_graph/update_reserved_instances.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/function_graph/v2/export_function.py
  otcextensions/sdk/function_graph/v2/import_function.py
  otcextensions/sdk/function_graph/v2/reserved_instance.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_import_export.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_reserved_instances.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_import_export.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_proxy.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_reserved_instances.py
Labels: enhancement, gate

#521 Added IMS image listing
  AUTHORS
  otcextensions/sdk/imsv2/v2/_proxy.py
  otcextensions/sdk/imsv2/v2/image.py
  otcextensions/tests/unit/sdk/imsv2/v2/test_image.py
  releasenotes/notes/imsv2_listing_images-542c27a5e8948bd7.yaml
Labels: enhancement, gate

#523 Fixes in FunctionGraph for _get_function_metadata and _get_function_code
  otcextensions/sdk/function_graph/v2/function.py
  releasenotes/notes/fg-functions-589e04d2107c7f1f.yaml
Labels: gate

#525 Fixes for VPC endpoint creation to include the port_ip parameter.
  otcextensions/sdk/vpcep/v1/_proxy.py
  otcextensions/sdk/vpcep/v1/endpoint.py
  releasenotes/notes/vpcep_endpoint_create_fix-03b19d669cd1428c.yaml
Labels: gate

#527 [Feat.] FunctionGraph Triggers
  .stestr.blacklist.functional
  doc/source/sdk/guides/function_graph.rst
  doc/source/sdk/proxies/function_graph.rst
  doc/source/sdk/resources/function_graph/index.rst
  doc/source/sdk/resources/function_graph/v2/trigger.rst
  examples/function_graph/create_trigger.py
  examples/function_graph/delete_all_triggers.py
  examples/function_graph/delete_trigger.py
  examples/function_graph/get_trigger.py
  examples/function_graph/list_triggers.py
  examples/function_graph/update_trigger.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/function_graph/v2/trigger.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_trigger.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_proxy.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_trigger.py
  releasenotes/notes/fg-triggers-e9d7744b9dedbd10.yaml
Labels: enhancement, gate

#528 [Fix] fixed base_path while create
  otcextensions/sdk/imsv2/v2/_proxy.py
  otcextensions/sdk/imsv2/v2/image.py
  otcextensions/tests/functional/sdk/imsv2/v2/test_image.py
Labels: bug, gate

#529 adding CFW, EVPN, GEMINIDB, HSS sdk proxies
  otcextensions/sdk/__init__.py
  otcextensions/sdk/cfwv1/__init__.py
  otcextensions/sdk/cfwv1/cfwv1_service.py
  otcextensions/sdk/cfwv1/v1/__init__.py
  otcextensions/sdk/cfwv1/v1/_proxy.py
  otcextensions/sdk/cfwv2/__init__.py
  otcextensions/sdk/cfwv2/cfwv2_service.py
  otcextensions/sdk/cfwv2/v2/__init__.py
  otcextensions/sdk/cfwv2/v2/_proxy.py
  otcextensions/sdk/cfwv3/__init__.py
  otcextensions/sdk/cfwv3/cfwv3_service.py
  otcextensions/sdk/cfwv3/v3/__init__.py
  otcextensions/sdk/cfwv3/v3/_proxy.py
  otcextensions/sdk/evpn/__init__.py
  otcextensions/sdk/evpn/evpn_service.py
  otcextensions/sdk/evpn/v5/__init__.py
  otcextensions/sdk/evpn/v5/_proxy.py
  otcextensions/sdk/geminidb/__init__.py
  otcextensions/sdk/geminidb/geminidb_service.py
  otcextensions/sdk/geminidb/v3/__init__.py
  otcextensions/sdk/geminidb/v3/_proxy.py
  otcextensions/sdk/hss/__init__.py
  otcextensions/sdk/hss/hss_service.py
  otcextensions/sdk/hss/v5/__init__.py
  otcextensions/sdk/hss/v5/_proxy.py
Labels: gate

#531 [Feat.] FunctionGraph Async Notification and Async Requests
  doc/source/sdk/guides/function_graph.rst
  doc/source/sdk/proxies/function_graph.rst
  doc/source/sdk/resources/function_graph/index.rst
  doc/source/sdk/resources/function_graph/v2/notification.rst
  examples/function_graph/configure_async_notification.py
  examples/function_graph/delete_async_notification.py
  examples/function_graph/list_all_async_notifications.py
  examples/function_graph/list_async_invocation_requests.py
  examples/function_graph/list_async_notifications.py
  examples/function_graph/stop_async_invocation_request.py
  otcextensions/sdk/function_graph/v2/_proxy.py
  otcextensions/sdk/function_graph/v2/async_notification.py
  otcextensions/tests/functional/sdk/function_graph/v2/test_async_notification.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_async_notification.py
  otcextensions/tests/unit/sdk/function_graph/v2/test_proxy.py
  releasenotes/notes/fg-notification-7c7bf9611687fc8f.yaml
Labels: enhancement, gate

#533 [Fix] missing gaussdb endpoint
  otcextensions/sdk/__init__.py
  otcextensions/tests/functional/sdk/gaussdb/__init__.py
  otcextensions/tests/functional/sdk/gaussdb/v3/__init__.py
  otcextensions/tests/functional/sdk/gaussdb/v3/test_service.py
  releasenotes/notes/gaussdb-service-fix-cf29eb96c5974a0d.yaml
Labels: bug, gate

#534 [Feat.] DDM proxies
  otcextensions/sdk/__init__.py
  otcextensions/sdk/ddmv1/__init__.py
  otcextensions/sdk/ddmv1/ddmv1_service.py
  otcextensions/sdk/ddmv1/v1/__init__.py
  otcextensions/sdk/ddmv1/v1/_proxy.py
  otcextensions/sdk/ddmv2/__init__.py
  otcextensions/sdk/ddmv2/ddmv2_service.py
  otcextensions/sdk/ddmv2/v1/__init__.py
  otcextensions/sdk/ddmv2/v1/_proxy.py
  otcextensions/sdk/ddmv3/__init__.py
  otcextensions/sdk/ddmv3/ddmv3_service.py
  otcextensions/sdk/ddmv3/v1/__init__.py
  otcextensions/sdk/ddmv3/v1/_proxy.py
  otcextensions/tests/functional/sdk/ddm/__init__.py
  otcextensions/tests/functional/sdk/ddm/v1/__init__.py
  otcextensions/tests/functional/sdk/ddm/v1/test_service.py
  otcextensions/tests/functional/sdk/ddm/v2/__init__.py
  otcextensions/tests/functional/sdk/ddm/v2/test_service.py
  otcextensions/tests/functional/sdk/ddm/v3/__init__.py
  otcextensions/tests/functional/sdk/ddm/v3/test_service.py
  releasenotes/notes/ddm-proxies-0df8caad363ff6b8.yaml
Labels: enhancement, gate

#535 [Feat.] APIG environment variables
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/env_var.rst
  examples/apig/create_env_variable.py
  examples/apig/delete_env_variable.py
  examples/apig/get_env_variable.py
  examples/apig/list_env_variables.py
  examples/apig/update_env_variable.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/apienvironmentvar.py
  otcextensions/tests/functional/sdk/apig/v2/test_environment_var.py
  otcextensions/tests/unit/sdk/apig/v2/test_env_var.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
Labels: enhancement, gate

#536 [Feat.] APIG Throttling Policy
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/throttling_policy.rst
  examples/apig/create_throttling_policy.py
  examples/apig/delete_throttling_policy.py
  examples/apig/get_throttling_policy.py
  examples/apig/list_throttling_policies.py
  examples/apig/update_throttling_policy.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/throttling_policy.py
  otcextensions/tests/functional/sdk/apig/v2/test_environment_var.py
  otcextensions/tests/functional/sdk/apig/v2/test_throttling_policy.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  otcextensions/tests/unit/sdk/apig/v2/test_throttling_policy.py
  releasenotes/notes/apig-environment-variables-ce4615fbf091dcf8.yaml
  releasenotes/notes/apig-throttling-policy-7b16352f6357e45d.yaml
Labels: enhancement, gate

#537 [Feat.] APIG API basic methods
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/api.rst
  examples/apig/create_api.py
  examples/apig/delete_api.py
  examples/apig/get_api.py
  examples/apig/list_apis.py
  examples/apig/update_api.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/api.py
  otcextensions/tests/functional/sdk/apig/v2/test_api.py
  otcextensions/tests/unit/sdk/apig/v2/test_api.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
Labels: enhancement, gate

#539 [Feat.] APIG API supplement methods
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/api_supplements.rst
  examples/apig/check_api.py
  examples/apig/debug_api.py
  examples/apig/list_api_runtime_definitions.py
  examples/apig/list_api_version_details.py
  examples/apig/list_api_versions.py
  examples/apig/offline_api.py
  examples/apig/offline_api_version.py
  examples/apig/offline_apis.py
  examples/apig/publish_api.py
  examples/apig/publish_apis.py
  examples/apig/switch_api_version.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/api_supplements.py
  otcextensions/tests/functional/sdk/apig/v2/test_api.py
  otcextensions/tests/unit/sdk/apig/v2/test_api.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  releasenotes/notes/apig-api-supplement-endpoints-8f235c0fa0b97438.yaml
Labels: enhancement, gate

#541 [Fix] Obs multipart name extraction fix
  doc/source/sdk/guides/index.rst
  doc/source/sdk/guides/obs.rst
  examples/obs/multipart_upload.py
  otcextensions/sdk/obs/v1/_proxy.py
  otcextensions/sdk/obs/v1/container.py
  releasenotes/notes/obs-multipart-fix-bc1cbba753bfafbd.yaml
Labels: bug, gate

#543 [Feat.] Signature keys
  doc/source/sdk/guides/apig.rst
  doc/source/sdk/proxies/apig.rst
  doc/source/sdk/resources/apig/index.rst
  doc/source/sdk/resources/apig/v2/signature.rst
  examples/apig/create_signature.py
  examples/apig/delete_signature.py
  examples/apig/list_signatures.py
  examples/apig/update_signature.py
  otcextensions/sdk/apig/v2/_proxy.py
  otcextensions/sdk/apig/v2/signature.py
  otcextensions/tests/functional/sdk/apig/v2/test_signature.py
  otcextensions/tests/unit/sdk/apig/v2/test_proxy.py
  otcextensions/tests/unit/sdk/apig/v2/test_signature.py
  releasenotes/notes/apig-signature-key-93971afc986fa60f.yaml
Labels: enhancement, gate

#545 [Fix] explicit header fix in multipart upload
  examples/obs/multipart_upload.py
  otcextensions/sdk/obs/v1/obj.py
  otcextensions/tests/unit/sdk/obs/v1/test_obj.py
  releasenotes/notes/obs-multipart-header-5265d7921c0d657a.yaml
Labels: bug, gate
